// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSale = `-- name: CreateSale :one
INSERT INTO sales (
  type, date, amount, category
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, type, date, amount, category
`

type CreateSaleParams struct {
	Type     TransactionType
	Date     pgtype.Date
	Amount   pgtype.Numeric
	Category pgtype.Text
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.Type,
		arg.Date,
		arg.Amount,
		arg.Category,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Date,
		&i.Amount,
		&i.Category,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM sales
WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, type, date, amount, category FROM sales
`

// CRUD --
func (q *Queries) GetAll(ctx context.Context) ([]Sale, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sale
	for rows.Next() {
		var i Sale
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Date,
			&i.Amount,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAverage = `-- name: GetAverage :one
SELECT AVG(amount) FROM sales
WHERE date >= $1 AND date <= $2
`

type GetAverageParams struct {
	Date   pgtype.Date
	Date_2 pgtype.Date
}

func (q *Queries) GetAverage(ctx context.Context, arg GetAverageParams) (float64, error) {
	row := q.db.QueryRow(ctx, getAverage, arg.Date, arg.Date_2)
	var avg float64
	err := row.Scan(&avg)
	return avg, err
}

const getByCategory = `-- name: GetByCategory :many
SELECT id, type, date, amount, category FROM sales
WHERE category = $1
`

func (q *Queries) GetByCategory(ctx context.Context, category pgtype.Text) ([]Sale, error) {
	rows, err := q.db.Query(ctx, getByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sale
	for rows.Next() {
		var i Sale
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Date,
			&i.Amount,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getById = `-- name: GetById :one
SELECT id, type, date, amount, category FROM sales
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetById(ctx context.Context, id int64) (Sale, error) {
	row := q.db.QueryRow(ctx, getById, id)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Date,
		&i.Amount,
		&i.Category,
	)
	return i, err
}

const getDateInterval = `-- name: GetDateInterval :many
SELECT id, type, date, amount, category FROM sales
WHERE date >= $1 AND date <= $2
`

type GetDateIntervalParams struct {
	Date   pgtype.Date
	Date_2 pgtype.Date
}

func (q *Queries) GetDateInterval(ctx context.Context, arg GetDateIntervalParams) ([]Sale, error) {
	rows, err := q.db.Query(ctx, getDateInterval, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sale
	for rows.Next() {
		var i Sale
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Date,
			&i.Amount,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMedian = `-- name: GetMedian :one
SELECT
percentile_cont(0.5) WITHIN GROUP (ORDER BY amount) AS median
FROM sales
WHERE date >= $1 AND date <= $2
`

type GetMedianParams struct {
	Date   pgtype.Date
	Date_2 pgtype.Date
}

func (q *Queries) GetMedian(ctx context.Context, arg GetMedianParams) (float64, error) {
	row := q.db.QueryRow(ctx, getMedian, arg.Date, arg.Date_2)
	var median float64
	err := row.Scan(&median)
	return median, err
}

const getPercentile = `-- name: GetPercentile :one
SELECT
percentile_cont($1) WITHIN GROUP (ORDER BY amount) AS median
FROM sales
WHERE date >= $2 AND date <= $3
`

type GetPercentileParams struct {
	PercentileCont float64
	Date           pgtype.Date
	Date_2         pgtype.Date
}

func (q *Queries) GetPercentile(ctx context.Context, arg GetPercentileParams) (float64, error) {
	row := q.db.QueryRow(ctx, getPercentile, arg.PercentileCont, arg.Date, arg.Date_2)
	var median float64
	err := row.Scan(&median)
	return median, err
}

const getSum = `-- name: GetSum :one
SELECT SUM(amount) FROM sales
WHERE date >= $1 AND date <= $2
`

type GetSumParams struct {
	Date   pgtype.Date
	Date_2 pgtype.Date
}

// ANALYTICS --
func (q *Queries) GetSum(ctx context.Context, arg GetSumParams) (int64, error) {
	row := q.db.QueryRow(ctx, getSum, arg.Date, arg.Date_2)
	var sum int64
	err := row.Scan(&sum)
	return sum, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE sales
  set category = $2,
  date = $3,
  amount = $4
WHERE id = $1
RETURNING id, type, date, amount, category
`

type UpdateItemParams struct {
	ID       int64
	Category pgtype.Text
	Date     pgtype.Date
	Amount   pgtype.Numeric
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Sale, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ID,
		arg.Category,
		arg.Date,
		arg.Amount,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Date,
		&i.Amount,
		&i.Category,
	)
	return i, err
}
