// Code generated by MockGen. DO NOT EDIT.
// Source: l0/back/db/db.go
//
// Generated by this command:
//
//	mockgen -source=l0/back/db/db.go -destination=l0/back/mocks/mock_db.go
//

// Package mock_db is a generated GoMock package.
package mocks

import (
	db "l0/db"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDBInterface is a mock of DBInterface interface.
type MockDBInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDBInterfaceMockRecorder
	isgomock struct{}
}

// MockDBInterfaceMockRecorder is the mock recorder for MockDBInterface.
type MockDBInterfaceMockRecorder struct {
	mock *MockDBInterface
}

// NewMockDBInterface creates a new mock instance.
func NewMockDBInterface(ctrl *gomock.Controller) *MockDBInterface {
	mock := &MockDBInterface{ctrl: ctrl}
	mock.recorder = &MockDBInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBInterface) EXPECT() *MockDBInterfaceMockRecorder {
	return m.recorder
}

// AddOrder mocks base method.
func (m *MockDBInterface) AddOrder(order *db.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrder", order)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrder indicates an expected call of AddOrder.
func (mr *MockDBInterfaceMockRecorder) AddOrder(order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrder", reflect.TypeOf((*MockDBInterface)(nil).AddOrder), order)
}

// GetAllOrders mocks base method.
func (m *MockDBInterface) GetAllOrders(limit, offset int) ([]db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrders", limit, offset)
	ret0, _ := ret[0].([]db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOrders indicates an expected call of GetAllOrders.
func (mr *MockDBInterfaceMockRecorder) GetAllOrders(limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrders", reflect.TypeOf((*MockDBInterface)(nil).GetAllOrders), limit, offset)
}

// GetOrderById mocks base method.
func (m *MockDBInterface) GetOrderById(id string) (*db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderById", id)
	ret0, _ := ret[0].(*db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderById indicates an expected call of GetOrderById.
func (mr *MockDBInterfaceMockRecorder) GetOrderById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderById", reflect.TypeOf((*MockDBInterface)(nil).GetOrderById), id)
}

// HasOrders mocks base method.
func (m *MockDBInterface) HasOrders() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasOrders")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasOrders indicates an expected call of HasOrders.
func (mr *MockDBInterfaceMockRecorder) HasOrders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasOrders", reflect.TypeOf((*MockDBInterface)(nil).HasOrders))
}
