// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg

type Message struct {
	ID        int64
	Body      string
	SendAt    string
	WasSentAt string
	Status    string
	Tries     int32
}
